import 'dart:math';

/// Generates friendly two-word device aliases like "Brave Peacock".
class AliasGenerator {
  AliasGenerator._();

  static const List<String> adjectives = [
    'Brave',
    'Calm',
    'Clever',
    'Cosmic',
    'Crisp',
    'Curious',
    'Daring',
    'Eager',
    'Fancy',
    'Gentle',
    'Golden',
    'Happy',
    'Jolly',
    'Kind',
    'Lucky',
    'Mellow',
    'Merry',
    'Mighty',
    'Nimble',
    'Noble',
    'Proud',
    'Quick',
    'Quiet',
    'Royal',
    'Shiny',
    'Silent',
    'Smart',
    'Sunny',
    'Swift',
    'Tidy',
    'Vivid',
    'Witty',
    'Zesty',
    'Bold',
    'Bright',
    'Breezy',
    'Cheery',
    'Dreamy',
    'Funky',
    'Lively',
  ];

  static const List<String> animals = [
    'Peacock',
    'Tiger',
    'Elephant',
    'Panda',
    'Dolphin',
    'Falcon',
    'Koala',
    'Lynx',
    'Otter',
    'Parrot',
    'Penguin',
    'Rabbit',
    'Sparrow',
    'Turtle',
    'Walrus',
    'Zebra',
    'Badger',
    'Camel',
    'Cheetah',
    'Crane',
    'Deer',
    'Eagle',
    'Fox',
    'Gazelle',
    'Heron',
    'Ibis',
    'Jaguar',
    'Kiwi',
    'Lemur',
    'Macaw',
    'Narwhal',
    'Owl',
    'Puffin',
    'Quail',
    'Raven',
    'Seal',
    'Swan',
    'Toucan',
    'Yak',
    'Wolf',
    'Mongoose',
    'Cobra',
    'Leopard',
    'Rhino',
    'Lion',
  ];

  static String generate([Random? random]) {
    final r = random ?? Random();
    return '${adjectives[r.nextInt(adjectives.length)]} '
        '${animals[r.nextInt(animals.length)]}';
  }
}
